# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{date_time_picker}
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Artem Rufanov"]
  s.date = %q{2011-12-25}
  s.description = %q{A library allows to select date and time.}
  s.email = %q{developers@majoron.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = Dir.glob('**/*') - Dir.glob('distrib/**/*') - Dir.glob('lib/api/**/*') - Dir.glob('doc/*.xpr')
  s.homepage = %q{http://www.majoron.com/project/rbundle/date_time_picker}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{date_time_picker}
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{A library allows to select date and time.}
  s.test_files = Dir.glob('spec/**/*')
  s.add_runtime_dependency 'nokogiri', '>= 1.4.5'

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

